spring.application.name=platform
# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/elearning}
spring.datasource.username=${USER_DB:postgres}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
frontend.valuable=${FRONTEND_VALUABLE:*}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET}
jwt.issuer=e-learning-platform